<a href="https://colab.research.google.com/github/apim0001/DeepLearning-Pytorch/blob/master/deep_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
x = torch.Tensor([5, 3])
y = torch.Tensor([4, 6])

In [10]:
x*y

tensor([20., 18.])

In [20]:
z = torch.zeros(5,2)
z

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [21]:
z.shape

torch.Size([5, 2])

In [22]:
z = torch.rand([5,2])
z

tensor([[0.1568, 0.8392],
        [0.2655, 0.6396],
        [0.0923, 0.9869],
        [0.2294, 0.1215],
        [0.9401, 0.4395]])

In [25]:
z = z.view([1,10])
z

tensor([[0.1568, 0.8392, 0.2655, 0.6396, 0.0923, 0.9869, 0.2294, 0.1215, 0.9401,
         0.4395]])